# Generated by Django 6.1 on 2026-08-06 08:32

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('industry_name', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CashCuttingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Cash Cutting', max_length=100)),
                ('rate_percent', models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Deduction percentage on gross purchase amount (e.g. 5.00 = Rs.50 per Rs.1000).', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('effective_from', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LivePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('price_per_quintal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('source', models.CharField(choices=[('LIVE', 'Fetched Live'), ('MANUAL', 'Manual Entry')], default='MANUAL', max_length=10)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', '-fetched_at'],
            },
        ),
        migrations.CreateModel(
            name='TareRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Bag Tare', max_length=100)),
                ('weight_per_bag_kg', models.DecimalField(decimal_places=3, default=Decimal('0.500'), help_text='Weight deducted per bag in KG (e.g. 0.5 for 500 g).', max_digits=6)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('unit', models.CharField(choices=[('KG', 'Kilogram'), ('QTL', 'Quintal (100 kg)')], default='QTL', max_length=3)),
                ('manual_price_per_quintal', models.DecimalField(blank=True, decimal_places=2, help_text='Used only if no live price is selected above.', max_digits=10, null=True)),
                ('gross_weight_kg', models.DecimalField(decimal_places=3, default=0, editable=False, max_digits=10)),
                ('num_bags', models.PositiveIntegerField(default=0, editable=False)),
                ('tare_weight_kg', models.DecimalField(decimal_places=3, default=0, editable=False, max_digits=10)),
                ('net_weight_kg', models.DecimalField(decimal_places=3, default=0, editable=False, max_digits=10)),
                ('price_used_per_quintal', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('gross_amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('cash_cutting_amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('net_payable', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cash_cutting_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.cashcuttingrule')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='core.client')),
                ('live_price', models.ForeignKey(blank=True, help_text='Leave blank to use the manual price below instead.', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.liveprice')),
                ('tare_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.tarerule')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('category', models.CharField(choices=[('CASH_EXTRA', 'Extra Cash Given (purchase/delivery)'), ('LABOUR', 'Labour Cost'), ('TRANSPORT', 'Vehicle / Transport Rent'), ('SHOP_RENT', 'Shop Rent'), ('LOADING', 'Loading / Unloading'), ('OTHER', 'Other')], max_length=15)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extra_costs', to='core.purchase')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('unit', models.CharField(choices=[('KG', 'Kilogram'), ('QTL', 'Quintal (100 kg)')], default='QTL', max_length=3)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='core.buyer')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseBag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bag_number', models.PositiveIntegerField()),
                ('weight_kg', models.DecimalField(decimal_places=3, max_digits=8)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bags', to='core.purchase')),
            ],
            options={
                'ordering': ['bag_number'],
                'unique_together': {('purchase', 'bag_number')},
            },
        ),
    ]
