# Generated by Django 5.2.17 on 2026-09-16 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='custom_cash_cutting_rate_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Custom cash-cutting % for this purchase only.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='custom_tare_per_bag_kg',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Custom tare (kg per bag) for this purchase only.', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cashcuttingrule',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='client',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='liveprice',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='cash_cutting_rule',
            field=models.ForeignKey(blank=True, help_text='Leave blank if entering a custom rate below.', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.cashcuttingrule'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='tare_rule',
            field=models.ForeignKey(blank=True, help_text='Leave blank if entering a custom tare below.', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.tarerule'),
        ),
        migrations.AlterField(
            model_name='purchasebag',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tarerule',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
