# Generated by Django 5.2.17 on 2026-09-17 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_investment'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='gross_amount_type_a',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12),
        ),
        migrations.AddField(
            model_name='purchase',
            name='gross_amount_type_b',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12),
        ),
        migrations.AddField(
            model_name='purchase',
            name='gross_amount_type_c',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12),
        ),
        migrations.AddField(
            model_name='purchase',
            name='net_weight_type_a_kg',
            field=models.DecimalField(decimal_places=3, default=0, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='purchase',
            name='net_weight_type_b_kg',
            field=models.DecimalField(decimal_places=3, default=0, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='purchase',
            name='net_weight_type_c_kg',
            field=models.DecimalField(decimal_places=3, default=0, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='purchase',
            name='price_type_b_per_quintal',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price per quintal for Type B (average) bags in this purchase.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='price_type_c_per_quintal',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price per quintal for Type C (poor) bags in this purchase.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='purchasebag',
            name='grade',
            field=models.CharField(choices=[('A', 'Type A - Best'), ('B', 'Type B - Average'), ('C', 'Type C - Poor')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='manual_price_per_quintal',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Used only if no live price is selected above. This is the Type A price.', max_digits=10, null=True),
        ),
    ]
