# Generated by Django 5.2.17 on 2026-09-18 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_purchase_gross_amount_type_a_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='custom_tare_big_kg',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Custom tare (kg) for Big bags in this purchase only. Leave blank to use the default (1.0 kg unless a TareRule says otherwise).', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='custom_tare_small_kg',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Custom tare (kg) for Small bags in this purchase only. Leave blank to use the default (0.5 kg unless a TareRule says otherwise).', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='purchasebag',
            name='bag_size',
            field=models.CharField(choices=[('BIG', 'Big'), ('SMALL', 'Small')], default='BIG', max_length=5),
        ),
        migrations.AddField(
            model_name='tarerule',
            name='bag_size',
            field=models.CharField(choices=[('BIG', 'Big'), ('SMALL', 'Small')], default='BIG', max_length=5),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='custom_tare_per_bag_kg',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Deprecated — superseded by custom_tare_big_kg / custom_tare_small_kg below. Kept for backward compatibility, no longer used in calculations.', max_digits=6, null=True),
        ),
    ]
